name: Build

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules and build
        id: node_build-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            public
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-

      - name: Install Packages
        if: steps.node_build-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Gatsby Build
        run: |
          npm run clean
          npm run build
